version: '2.1'
services:
  kemono-cache:
    image: healthcheck/redis
    container_name: kemono-cache
    command: ["redis-server", "--appendonly", "no"]
    volumes:
      - cache-data:/data
    restart: unless-stopped
    # ports:
    #  - 6739:6739
  kemono-db:
    image: healthcheck/postgres
    container_name: kemono-db
    environment:
      - POSTGRES_USER=nano
      - POSTGRES_PASSWORD=shinonome
      - POSTGRES_DB=kemonodb
    volumes:
      - db-data:/var/lib/postgresql/data/
    restart: unless-stopped
    # ports:
    #  - 5432:5432
  kemono-app:
    build: .
    container_name: kemono
    restart: unless-stopped
    depends_on:
      kemono-db:
        condition: service_healthy
      kemono-cache:
        condition: service_healthy
    ports:
      - 8000:8000
    env_file:
      - .env
    environment:
      - PGUSER=nano
      - PGPASSWORD=shinonome
      - PGDATABASE=kemonodb
      - PGHOST=kemono-db
      - RDHOST=kemono-cache
    volumes:
      - data:/storage
volumes:
  # If you need to store your volumes manually, uncomment the "driver_opts" lines and specify your "device" location.
  cache-data:
    driver: local
    # driver_opts:
    #   type: 'none'
    #   o: 'bind'
    #   device: "/mnt/slab1/kemono-cache"
  db-data:
    driver: local
    # driver_opts:
    #   type: 'none'
    #   o: 'bind'
    #   device: "/mnt/slab1/kemono-db"
  data:
    driver: local
    # driver_opts:
    #   type: 'none'
    #   o: 'bind'
    #   device: "/mnt/slab1/kemono"