name: buildx
on:
  pull_request:
    types: [closed]
    branches: party
  push:
    branches: party

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
        with:
          ref: "party"
      -
        name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - 
        name: Docker login
        run: |
          docker login -u "${DOCKER_REGISTRY_USERNAME}" -p "${DOCKER_REGISTRY_PASSWORD}"
        env:
          DOCKER_REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          DOCKER_REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      -
        name: Run Buildx
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            --output "type=image,push=true" \
            --tag openyiff/kemono:latest \
            --file ./Dockerfile .
        env:
          PUBLIC_ORIGIN: ${{ secrets.PUBLIC_ORIGIN }}
          FANBOX_KEY: ${{ secrets.FANBOX_KEY }}
          ADMIN_CAPCODE: ${{ secrets.ADMIN_CAPCODE }}
          MASTER_KEY: ${{ secrets.MASTER_KEY }}
      - 
        name: Docker logout
        run: |
          docker logout
        env:
          DOCKER_REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}